markdown: redcarpet
permalink: /:year/:month/:day/:title.html
url: 
lsi: false
pygments: true
safe: false
auto: false 

paginate: 10
paginate_path: "page:num"

# presonal config
title: 94geek
description: 94geek.com,blog of Seapeak.Xu,powered by Jekyll...
feed: http://www.94geek.com/atom.xml

author: Seapeak.Xu

seo: 
  keyword: 94geek,geek,geeker,seapeak,linux,c,java,c#,albian,albianj,libev,
    算法,libev中文文档,编程,极客,架构设计,架构师
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
